sudo: required
services:
    - docker

before_install:
    - docker build -t aswwsa/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run aswwsa/react-test npm test -- --coverage

after_success:
    - docker build -t aswwsa/multi-client -f ./client
    - docker build -t aswwsa/multi-nginx -f ./nginx
    - docker build -t aswwsa/multi-server -f ./server
    - docker build -t aswwsa/multi-worker -f ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push aswwsa/multi-client
    - docker push aswwsa/multi-nginx
    - docker push aswwsa/multi-server
    - docker push aswwsa/multi-worker
