language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t aswwsa/react-test -f ./client/Dockerfile.dev ./client

# script:
# - docker run -e CI=true aswwsa/react-test npm run test -- --coverage

after_success:
  - docker build -t aswwsa/multi-client ./client
  - docker build -t aswwsa/multi-nginx ./nginx
  - docker build -t aswwsa/multi-server ./server
  - docker build -t aswwsa/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push aswwsa/multi-client
  - docker push aswwsa/multi-nginx
  - docker push aswwsa/multi-server
  - docker push aswwsa/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "multi-docker"
  env: "MultiDocker-env-1"
  bucket_name: "elasticbeanstalk-ap-southeast-2-001983725908"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
